### ISSUE TITLE
nextgenrepl_aaefold test fails on riak-3.0.15

### ISSUE THREAD

**Issue by fadushin** [basho/riak_test#1376]
The `nextgenrepl_aaefold` test appears to be failing consistently when run over riak-3.0.15.

Steps to reproduce:

1. Build riak-3.0.15 (using `riak-3.0.15` tag) using `make stagedevrel` target (using OTP 22)
2. Deploy `riak-3.0.15` devrels into riak_test staging area (in my case, `$HOME/work/rt/riak`)
3. Build `riak_test`.  In this case, because riak_test does not appear to be tagged, I used commit `f2e02777722a36407cc077031d5a738d657afc8a`
4. Set up `$HOME/.riak_test.config` to point to staged `riak-3.0.15` devrels
5. Run `./riak_test -c riak -t nextgenrepl_aaefold`

The test fails on line 250 of the test with:

```
13:35:32.684 [warning] <0.9.0> nextgenrepl_aaefold failed: {{badmatch,1000},[{nextgenrepl_aaefold,confirm,0,[{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/tests/nextgenrepl_aaefold.erl"},{line,250}]},{riak_test_runner,return_to_exit,3,[{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/src/riak_test_runner.erl"},{line,159}]}]}
13:35:32.684 [error] <0.9.0> 
================ nextgenrepl_aaefold failure stack trace =====================
{{badmatch,1000},
 [{nextgenrepl_aaefold,confirm,0,
                       [{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/tests/nextgenrepl_aaefold.erl"},
                        {line,250}]},
  {riak_test_runner,return_to_exit,3,
                    [{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/src/riak_test_runner.erl"},
                     {line,159}]}]}
==============================================================================

13:35:32.684 [notice] <0.9.0> nextgenrepl_aaefold Test Run Complete fail
13:35:32.685 [error] emulator Error in process <0.185.0> on node 'riak_test@127.0.0.1' with exit value:
{{badmatch,1000},[{nextgenrepl_aaefold,confirm,0,[{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/tests/nextgenrepl_aaefold.erl"},{line,250}]},{riak_test_runner,return_to_exit,3,[{file,"/Users/fadushin/work/src/github/basho/riak_test-3.0.15/src/riak_test_runner.erl"},{line,159}]}]}
```

Tested on MacOS 11.7.6, Intel core i7 32G RAM

**Comment by martinsumner** [comment]
I just did a quick check on my current setup (I have a branch based on 3.0.15 with some unrelated updates, and riak_test `develop-3.0`).  The test passed for me.

Is this a general problem across multiple tests (for instance are the other tests in the nextgenrepl group failing)?

My test setup is based on https://github.com/basho/riak_test/blob/develop-3.0/doc/SIMPLE_SETUP.md.  I'm running OSX, but a more current version and M1.  The test also passes in our Ubuntu based CI environment.

**Comment by fadushin** [comment]
Excellent, great to hear.  It is failing consistently for me locally and in CI (though on a slightly different but not too different branch), but I will keep trying.  And yes, there are some other nextgenrepl tests that are also failing in CI, but they do pass locally.

Closing this ticket as "not reproducible".  Could very well be a resource issue on my end.  (And yes, I wish I had an M* CPU... :)
