### ISSUE TITLE
riak_test for 2.0.5 failing due to incomplete stats list

### ISSUE THREAD

**Issue by macintux** [basho/riak_test#731]
After changes to `riak_kv_stats` the `verify_riak_stats` module no longer passes.

This change seems appropriate regardless:
```
--- a/tests/verify_riak_stats.erl
+++ b/tests/verify_riak_stats.erl
@@ -218,7 +218,7 @@ diff_lists(List, ThatList) ->
 -spec maybe_log_stats_keys([binary()], string()) -> ok.
 maybe_log_stats_keys(StatsKeys, _Description) when length(StatsKeys) == 0 ->
     ok;
-maybe_log_stats_keys(StatsKeys, Description) when StatsKeys ->
+maybe_log_stats_keys(StatsKeys, Description) ->
     lager:info("~s: ~s", [Description, pretty_print_stats_keys(StatsKeys)]).

 -spec pretty_print_stats_keys([binary()]) -> string().
```

These stats are not predefined in the module and are throwing an error as "additional stats":
```
vnode_get_fsm_time_99, vnode_put_fsm_time_mean, vnode_get_fsm_time_95, vnode_put_fsm_time_99, vnode_put_fsm_time_median, vnode_put_fsm_time_95, vnode_put_fsm_time_100, vnode_get_fsm_time_median, vnode_get_fsm_time_100, vnode_get_fsm_time_mean
```

**Comment by macintux** [comment]
Result of https://github.com/basho/riak_kv/pull/1075

**Comment by uwiger** [comment]
@macintux, that thread notes several times that verify_riak_stats.erl passed. Has something else changed since then?

**Comment by macintux** [comment]
This test hasn't changed on master since mid-December, which made me wonder if there was a riak_test branch that had not been committed, but there was no mention of that with the PR.

**Comment by cmeiklejohn** [comment]
But, the question isn't *when* it passed, but *where* it passed...

**Comment by HMcKelvey** [comment]
Hi JohnB and Ulf,
May we get this fixed for all future releases :-)
Thanks,
Heather

On Mon, Feb 9, 2015 at 12:49 PM, John Daily <notifications@github.com>
wrote:

> After changes to riak_kv_stats the verify_riak_stats module no longer
> passes.
>
> This change seems appropriate regardless:
>
> --- a/tests/verify_riak_stats.erl
> +++ b/tests/verify_riak_stats.erl
> @@ -218,7 +218,7 @@ diff_lists(List, ThatList) ->
>  -spec maybe_log_stats_keys([binary()], string()) -> ok.
>  maybe_log_stats_keys(StatsKeys, _Description) when length(StatsKeys) == 0 ->
>      ok;
> -maybe_log_stats_keys(StatsKeys, Description) when StatsKeys ->
> +maybe_log_stats_keys(StatsKeys, Description) ->
>      lager:info("~s: ~s", [Description, pretty_print_stats_keys(StatsKeys)]).
>
>  -spec pretty_print_stats_keys([binary()]) -> string().
>
> These stats are not predefined in the module and are throwing an error as
> "additional stats":
>
> vnode_get_fsm_time_99, vnode_put_fsm_time_mean, vnode_get_fsm_time_95, vnode_put_fsm_time_99, vnode_put_fsm_time_median, vnode_put_fsm_time_95, vnode_put_fsm_time_100, vnode_get_fsm_time_median, vnode_get_fsm_time_100, vnode_get_fsm_time_mean
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basho/riak_test/issues/731>.
>



-- 
Heather McKelvey
VP Engineering
Basho Technologies

**Comment by cmeiklejohn** [comment]
I already pushed and merged a fix for this.

- Chris

**Comment by jburwell** [comment]
Heather,

The test verifies that all of keys the stats list exactly match the keys returned from /stats.  By design, the test case must be updated whenever new stats are added.

The node_get_fsm stats defect was the result of the vnode_get_fsm stats getting remapped to node_get_fsm stats.  The fix exposed new stats that should have been present in 2.0.4, but didn't make the original test case.  

The test failure is my fault.  I ran the test case on PR review, and it passed.  However, I clearly pointed the riak_kv to the wrong branch causing me to believe it was passing.  

I apologize for the big miss,
-John

**Comment by HMcKelvey** [comment]
Thanks CMJ!

On Mon, Feb 9, 2015 at 3:02 PM, Christopher Meiklejohn <
notifications@github.com> wrote:

> I already pushed and merged a fix for this.
>
> - Chris
>
> > On Feb 9, 2015, at 6:00 PM, HMcKelvey <notifications@github.com> wrote:
> >
> > Hi JohnB and Ulf,
> > May we get this fixed for all future releases :-)
> > Thanks,
> > Heather
> >
> > On Mon, Feb 9, 2015 at 12:49 PM, John Daily <notifications@github.com>
> > wrote:
> >
> > > After changes to riak_kv_stats the verify_riak_stats module no longer
> > > passes.
> > >
> > > This change seems appropriate regardless:
> > >
> > > --- a/tests/verify_riak_stats.erl
> > > +++ b/tests/verify_riak_stats.erl
> > > @@ -218,7 +218,7 @@ diff_lists(List, ThatList) ->
> > > -spec maybe_log_stats_keys([binary()], string()) -> ok.
> > > maybe_log_stats_keys(StatsKeys, _Description) when length(StatsKeys)
> == 0 ->
> > > ok;
> > > -maybe_log_stats_keys(StatsKeys, Description) when StatsKeys ->
> > > +maybe_log_stats_keys(StatsKeys, Description) ->
> > > lager:info("~s: ~s", [Description,
> pretty_print_stats_keys(StatsKeys)]).
> > >
> > > -spec pretty_print_stats_keys([binary()]) -> string().
> > >
> > > These stats are not predefined in the module and are throwing an error
> as
> > > "additional stats":
> > >
> > > vnode_get_fsm_time_99, vnode_put_fsm_time_mean, vnode_get_fsm_time_95,
> vnode_put_fsm_time_99, vnode_put_fsm_time_median, vnode_put_fsm_time_95,
> vnode_put_fsm_time_100, vnode_get_fsm_time_median, vnode_get_fsm_time_100,
> vnode_get_fsm_time_mean
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/basho/riak_test/issues/731>.
> > >
> >
> >
> >
> > --
> > Heather McKelvey
> > VP Engineering
> > Basho Technologies
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/basho/riak_test/issues/731#issuecomment-73609658>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basho/riak_test/issues/731#issuecomment-73609958>.
>



-- 
Heather McKelvey
VP Engineering
Basho Technologies
