### ISSUE TITLE
Cuttlefishy riak_test for CS [JIRA: RCS-226]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_test#810]
Current riak_test only uses advanced.config or app.config generated. It should use riak-cs.conf as auto-generated configuration file.

**[Created in JIRA by Kota Uenishi]**

**Comment by kuenishi** [comment]
Looks like we can do it easily: https://github.com/basho/riak_test/blob/abe96250b8d759e594f296eab142c28b008b31ca/src/rtdev.erl#L161-L172

**Comment by kuenishi** [comment]
No, it is already done.

**Comment by kuenishi** [comment]
We'll continue work on CS repo.
